"""create new data table, delete bug tale

Revision ID: d84b65e76689
Revises: 0caef63c8762
Create Date: 2018-02-25 21:06:41.997716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd84b65e76689'
down_revision = '0caef63c8762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bug_tracker_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('root_cause', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('who', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('when', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bug_pkey')
    )
    op.drop_table('Data')
    # ### end Alembic commands ###
